from __future__ import annotations

PRODUCTION_PROFILE_INTERVAL = "15m"

PRODUCTION_STRATEGY_ALIASES: dict[str, str] = {
    "dual_thrust_breakout": "dual_thrust",
}

PRODUCTION_PROFILE_REGISTRY: dict[str, dict[str, object]] = {'1000PEPEUSDT': {'breakeven_activation_pct': 2.0,
                  'breakeven_buffer_pct': 0.2,
                  'default_leverage': 25,
                  'interval': '1h',
                  'stop_loss_pct': 1.0,
                  'strategy_name': 'ema_band_rejection',
                  'strategy_params': {'atr_length': 14.0,
                                      'atr_stop_buffer_mult': 0.5,
                                      'ema_fast': 5.0,
                                      'ema_mid': 10.0,
                                      'ema_slow': 20.0,
                                      'min_ema_spread_pct': 0.05,
                                      'min_slow_slope_pct': 0.0,
                                      'pullback_requires_outer_band_touch': 0.0,
                                      'rejection_body_min_ratio': 0.2,
                                      'rejection_wick_min_ratio': 0.35,
                                      'rsi_length': 14.0,
                                      'rsi_midline': 50.0,
                                      'rsi_midline_margin': 0.0,
                                      'signal_cooldown_bars': 3.0,
                                      'slope_lookback': 5.0,
                                      'use_atr_stop_buffer': 1.0,
                                      'use_rejection_quality_filter': 1.0,
                                      'use_rsi_cross_filter': 0.0,
                                      'use_rsi_filter': 1.0,
                                      'use_volume_filter': 0.0,
                                      'volume_ma_length': 20.0,
                                      'volume_multiplier': 1.0},
                  'take_profit_pct': 5.0,
                  'trailing_activation_pct': 2.0,
                  'trailing_distance_pct': 0.1},
 '1000SHIBUSDT': {'breakeven_activation_pct': 2.0,
                  'breakeven_buffer_pct': 0.2,
                  'default_leverage': 25,
                  'interval': '1h',
                  'stop_loss_pct': 1.5,
                  'strategy_name': 'ema_band_rejection',
                  'strategy_params': {'atr_length': 14.0,
                                      'atr_stop_buffer_mult': 0.5,
                                      'ema_fast': 5.0,
                                      'ema_mid': 10.0,
                                      'ema_slow': 20.0,
                                      'min_ema_spread_pct': 0.08,
                                      'min_slow_slope_pct': 0.0,
                                      'pullback_requires_outer_band_touch': 0.0,
                                      'rejection_body_min_ratio': 0.2,
                                      'rejection_wick_min_ratio': 0.35,
                                      'rsi_length': 14.0,
                                      'rsi_midline': 50.0,
                                      'rsi_midline_margin': 0.0,
                                      'signal_cooldown_bars': 3.0,
                                      'slope_lookback': 5.0,
                                      'use_atr_stop_buffer': 1.0,
                                      'use_rejection_quality_filter': 1.0,
                                      'use_rsi_cross_filter': 0.0,
                                      'use_rsi_filter': 1.0,
                                      'use_volume_filter': 0.0,
                                      'volume_ma_length': 20.0,
                                      'volume_multiplier': 1.0},
                  'take_profit_pct': 5.0,
                  'trailing_activation_pct': 2.0,
                  'trailing_distance_pct': 0.1},
 'AAVEUSDT': {'breakeven_activation_pct': 2.0,
              'breakeven_buffer_pct': 0.2,
              'default_leverage': 25,
              'interval': '1h',
              'stop_loss_pct': 1.0,
              'strategy_name': 'ema_band_rejection',
              'strategy_params': {'atr_length': 14.0,
                                  'atr_stop_buffer_mult': 0.5,
                                  'ema_fast': 5.0,
                                  'ema_mid': 10.0,
                                  'ema_slow': 20.0,
                                  'min_ema_spread_pct': 0.08,
                                  'min_slow_slope_pct': 0.02,
                                  'pullback_requires_outer_band_touch': 0.0,
                                  'rejection_body_min_ratio': 0.2,
                                  'rejection_wick_min_ratio': 0.35,
                                  'rsi_length': 14.0,
                                  'rsi_midline': 50.0,
                                  'rsi_midline_margin': 0.0,
                                  'signal_cooldown_bars': 0.0,
                                  'slope_lookback': 3.0,
                                  'use_atr_stop_buffer': 0.0,
                                  'use_rejection_quality_filter': 0.0,
                                  'use_rsi_cross_filter': 0.0,
                                  'use_rsi_filter': 1.0,
                                  'use_volume_filter': 1.0,
                                  'volume_ma_length': 20.0,
                                  'volume_multiplier': 1.25},
              'take_profit_pct': 5.0,
              'trailing_activation_pct': 2.0,
              'trailing_distance_pct': 0.1},
 'ADAUSDT': {'breakeven_activation_pct': 3.5,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 0.5,
             'strategy_name': 'dual_thrust',
             'strategy_params': {'chandelier_multiplier': 1.5,
                                 'chandelier_period': 14.0,
                                 'dual_thrust_k1': 0.2,
                                 'dual_thrust_k2': 0.2,
                                 'dual_thrust_period': 89.0},
             'take_profit_pct': 15.0,
             'tight_trailing_activation_pct': 8.0,
             'tight_trailing_distance_pct': 0.3,
             'trailing_activation_pct': 6.0,
             'trailing_distance_pct': 0.15},
 'ARBUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.0,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.08,
                                 'min_slow_slope_pct': 0.02,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 1.0,
                                 'signal_cooldown_bars': 0.0,
                                 'slope_lookback': 5.0,
                                 'use_atr_stop_buffer': 1.0,
                                 'use_rejection_quality_filter': 0.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 1.0,
                                 'use_volume_filter': 1.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 3.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1},
 'AVAXUSDT': {'breakeven_activation_pct': 2.0,
              'breakeven_buffer_pct': 0.2,
              'default_leverage': 25,
              'interval': '1h',
              'stop_loss_pct': 2.0,
              'strategy_name': 'ema_band_rejection',
              'strategy_params': {'atr_length': 14.0,
                                  'atr_stop_buffer_mult': 0.5,
                                  'ema_fast': 5.0,
                                  'ema_mid': 10.0,
                                  'ema_slow': 20.0,
                                  'min_ema_spread_pct': 0.05,
                                  'min_slow_slope_pct': 0.02,
                                  'pullback_requires_outer_band_touch': 0.0,
                                  'rejection_body_min_ratio': 0.2,
                                  'rejection_wick_min_ratio': 0.35,
                                  'rsi_length': 14.0,
                                  'rsi_midline': 50.0,
                                  'rsi_midline_margin': 0.0,
                                  'signal_cooldown_bars': 3.0,
                                  'slope_lookback': 3.0,
                                  'use_atr_stop_buffer': 0.0,
                                  'use_rejection_quality_filter': 1.0,
                                  'use_rsi_cross_filter': 0.0,
                                  'use_rsi_filter': 0.0,
                                  'use_volume_filter': 0.0,
                                  'volume_ma_length': 20.0,
                                  'volume_multiplier': 1.0},
              'take_profit_pct': 5.0,
              'trailing_activation_pct': 2.0,
              'trailing_distance_pct': 0.1},
 'BCHUSDT': {'breakeven_activation_pct': 5.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.5,
             'strategy_name': 'frama_cross',
             'strategy_params': {'chandelier_multiplier': 3.5,
                                 'chandelier_period': 14.0,
                                 'frama_fast_period': 13.0,
                                 'frama_slow_period': 60.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 3.5,
             'trailing_activation_pct': 5.0,
             'trailing_distance_pct': 0.1},
 'BNBUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.5,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.08,
                                 'min_slow_slope_pct': 0.02,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 0.0,
                                 'signal_cooldown_bars': 3.0,
                                 'slope_lookback': 3.0,
                                 'use_atr_stop_buffer': 0.0,
                                 'use_rejection_quality_filter': 0.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 0.0,
                                 'use_volume_filter': 0.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 5.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1},
 'BTCUSDT': {'breakeven_activation_pct': 5.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '15m',
             'stop_loss_pct': 3.0,
             'strategy_name': 'frama_cross',
             'strategy_params': {'chandelier_multiplier': 2.5,
                                 'chandelier_period': 14.0,
                                 'frama_fast_period': 13.0,
                                 'frama_slow_period': 200.0,
                                 'volume_multiplier': 2.5},
             'take_profit_pct': 7.5,
             'trailing_activation_pct': 7.5,
             'trailing_distance_pct': 0.1},
 'DOGEUSDT': {'breakeven_activation_pct': 3.5,
              'breakeven_buffer_pct': 0.2,
              'default_leverage': 25,
              'interval': '1h',
              'stop_loss_pct': 1.5,
              'strategy_name': 'dual_thrust',
              'strategy_params': {'chandelier_multiplier': 1.5,
                                  'chandelier_period': 14.0,
                                  'dual_thrust_k1': 0.5,
                                  'dual_thrust_k2': 0.3,
                                  'dual_thrust_period': 89.0},
              'take_profit_pct': 3.0,
              'tight_trailing_activation_pct': 8.0,
              'tight_trailing_distance_pct': 0.3,
              'trailing_activation_pct': 6.0,
              'trailing_distance_pct': 0.3},
 'DOTUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.5,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.05,
                                 'min_slow_slope_pct': 0.0,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 0.0,
                                 'signal_cooldown_bars': 3.0,
                                 'slope_lookback': 3.0,
                                 'use_atr_stop_buffer': 1.0,
                                 'use_rejection_quality_filter': 1.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 0.0,
                                 'use_volume_filter': 0.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 5.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1},
 'ETHUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.0,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.08,
                                 'min_slow_slope_pct': 0.0,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 1.0,
                                 'signal_cooldown_bars': 3.0,
                                 'slope_lookback': 3.0,
                                 'use_atr_stop_buffer': 0.0,
                                 'use_rejection_quality_filter': 0.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 1.0,
                                 'use_volume_filter': 1.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 5.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1},
 'FILUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.0,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.08,
                                 'min_slow_slope_pct': 0.02,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 0.0,
                                 'signal_cooldown_bars': 3.0,
                                 'slope_lookback': 3.0,
                                 'use_atr_stop_buffer': 0.0,
                                 'use_rejection_quality_filter': 0.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 0.0,
                                 'use_volume_filter': 1.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 3.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1},
 'LINKUSDT': {'breakeven_activation_pct': 2.0,
              'breakeven_buffer_pct': 0.2,
              'default_leverage': 25,
              'interval': '1h',
              'stop_loss_pct': 2.0,
              'strategy_name': 'ema_band_rejection',
              'strategy_params': {'atr_length': 14.0,
                                  'atr_stop_buffer_mult': 0.5,
                                  'ema_fast': 5.0,
                                  'ema_mid': 10.0,
                                  'ema_slow': 20.0,
                                  'min_ema_spread_pct': 0.05,
                                  'min_slow_slope_pct': 0.02,
                                  'pullback_requires_outer_band_touch': 0.0,
                                  'rejection_body_min_ratio': 0.2,
                                  'rejection_wick_min_ratio': 0.35,
                                  'rsi_length': 14.0,
                                  'rsi_midline': 50.0,
                                  'rsi_midline_margin': 0.0,
                                  'signal_cooldown_bars': 0.0,
                                  'slope_lookback': 3.0,
                                  'use_atr_stop_buffer': 1.0,
                                  'use_rejection_quality_filter': 1.0,
                                  'use_rsi_cross_filter': 0.0,
                                  'use_rsi_filter': 0.0,
                                  'use_volume_filter': 0.0,
                                  'volume_ma_length': 20.0,
                                  'volume_multiplier': 1.0},
              'take_profit_pct': 3.0,
              'trailing_activation_pct': 2.0,
              'trailing_distance_pct': 0.1},
 'LTCUSDT': {'breakeven_activation_pct': 5.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.5,
             'strategy_name': 'frama_cross',
             'strategy_params': {'chandelier_multiplier': 3.5,
                                 'chandelier_period': 30.0,
                                 'frama_fast_period': 13.0,
                                 'frama_slow_period': 100.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 3.5,
             'trailing_activation_pct': 5.0,
             'trailing_distance_pct': 0.1},
 'NEARUSDT': {'breakeven_activation_pct': 5.0,
              'breakeven_buffer_pct': 0.2,
              'default_leverage': 25,
              'interval': '15m',
              'stop_loss_pct': 3.0,
              'strategy_name': 'frama_cross',
              'strategy_params': {'chandelier_multiplier': 2.5,
                                  'chandelier_period': 30.0,
                                  'frama_fast_period': 21.0,
                                  'frama_slow_period': 60.0,
                                  'volume_multiplier': 1.5},
              'take_profit_pct': 5.0,
              'trailing_activation_pct': 5.0,
              'trailing_distance_pct': 0.1},
 'SOLUSDT': {'breakeven_activation_pct': 3.5,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '15m',
             'stop_loss_pct': 3.0,
             'strategy_name': 'frama_cross',
             'strategy_params': {'chandelier_multiplier': 2.5,
                                 'chandelier_period': 14.0,
                                 'frama_fast_period': 8.0,
                                 'frama_slow_period': 100.0,
                                 'volume_multiplier': 2.5},
             'take_profit_pct': 5.0,
             'trailing_activation_pct': 5.0,
             'trailing_distance_pct': 0.1},
 'SUIUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.5,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.05,
                                 'min_slow_slope_pct': 0.02,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 1.0,
                                 'signal_cooldown_bars': 3.0,
                                 'slope_lookback': 3.0,
                                 'use_atr_stop_buffer': 0.0,
                                 'use_rejection_quality_filter': 0.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 1.0,
                                 'use_volume_filter': 1.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 5.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1},
 'TRXUSDT': {'breakeven_activation_pct': 5.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '15m',
             'stop_loss_pct': 0.5,
             'strategy_name': 'frama_cross',
             'strategy_params': {'chandelier_multiplier': 2.5,
                                 'chandelier_period': 14.0,
                                 'frama_fast_period': 13.0,
                                 'frama_slow_period': 60.0,
                                 'volume_multiplier': 2.5},
             'take_profit_pct': 3.5,
             'trailing_activation_pct': 5.0,
             'trailing_distance_pct': 0.1},
 'XRPUSDT': {'breakeven_activation_pct': 2.0,
             'breakeven_buffer_pct': 0.2,
             'default_leverage': 25,
             'interval': '1h',
             'stop_loss_pct': 1.0,
             'strategy_name': 'ema_band_rejection',
             'strategy_params': {'atr_length': 14.0,
                                 'atr_stop_buffer_mult': 0.5,
                                 'ema_fast': 5.0,
                                 'ema_mid': 10.0,
                                 'ema_slow': 20.0,
                                 'min_ema_spread_pct': 0.05,
                                 'min_slow_slope_pct': 0.02,
                                 'pullback_requires_outer_band_touch': 0.0,
                                 'rejection_body_min_ratio': 0.2,
                                 'rejection_wick_min_ratio': 0.35,
                                 'rsi_length': 14.0,
                                 'rsi_midline': 50.0,
                                 'rsi_midline_margin': 0.0,
                                 'signal_cooldown_bars': 0.0,
                                 'slope_lookback': 5.0,
                                 'use_atr_stop_buffer': 0.0,
                                 'use_rejection_quality_filter': 0.0,
                                 'use_rsi_cross_filter': 0.0,
                                 'use_rsi_filter': 0.0,
                                 'use_volume_filter': 1.0,
                                 'volume_ma_length': 20.0,
                                 'volume_multiplier': 1.0},
             'take_profit_pct': 5.0,
             'trailing_activation_pct': 2.0,
             'trailing_distance_pct': 0.1}}

__all__ = (
    "PRODUCTION_PROFILE_INTERVAL",
    "PRODUCTION_STRATEGY_ALIASES",
    "PRODUCTION_PROFILE_REGISTRY",
)
