from __future__ import annotations

PRODUCTION_PROFILE_INTERVAL = "15m"

PRODUCTION_STRATEGY_ALIASES: dict[str, str] = {
    "dual_thrust_breakout": "dual_thrust",
}

PRODUCTION_PROFILE_REGISTRY: dict[str, dict[str, object]] = {
    "BTCUSDT": {
        "strategy_name": "frama_cross",
        "take_profit_pct": 8.0,
        "stop_loss_pct": 5.0,
        "trailing_activation_pct": 4.0,
        "trailing_distance_pct": 0.15,
        "default_leverage": 20,
        "strategy_params": {"frama_fast_period": 8.0, "frama_slow_period": 34.0},
        "audit_meta": {
            "profit_factor": 1.44,
            "pnl": 1884.22,
            "win_rate": 66.14,
            "trades": 381,
            "max_drawdown_pct": 8.17,
            "longest_consecutive_losses": 5,
        },
    },
    "ETHUSDT": {
        "strategy_name": "ema_cross_volume",
        "take_profit_pct": 7.0,
        "stop_loss_pct": 4.5,
        "trailing_activation_pct": 3.5,
        "trailing_distance_pct": 0.2,
        "default_leverage": 20,
        "strategy_params": {"ema_fast_period": 12.0, "ema_slow_period": 34.0},
        "audit_meta": {
            "profit_factor": 1.21,
            "pnl": 1508.96,
            "win_rate": 59.15,
            "trades": 661,
            "max_drawdown_pct": 9.67,
            "longest_consecutive_losses": 8,
        },
    },
    "SOLUSDT": {
        "strategy_name": "frama_cross",
        "take_profit_pct": 10.0,
        "stop_loss_pct": 5.5,
        "trailing_activation_pct": 4.5,
        "trailing_distance_pct": 0.15,
        "default_leverage": 20,
        "strategy_params": {"frama_fast_period": 10.0, "frama_slow_period": 21.0},
        "audit_meta": {
            "profit_factor": 1.51,
            "pnl": 5070.27,
            "win_rate": 63.45,
            "trades": 621,
            "max_drawdown_pct": 7.62,
            "longest_consecutive_losses": 5,
        },
    },
    "XRPUSDT": {
        "strategy_name": "ema_cross_volume",
        "take_profit_pct": 6.0,
        "stop_loss_pct": 4.0,
        "trailing_activation_pct": 3.0,
        "trailing_distance_pct": 0.25,
        "default_leverage": 20,
        "strategy_params": {"ema_fast_period": 9.0, "ema_slow_period": 21.0},
        "audit_meta": {
            "profit_factor": 1.35,
            "pnl": 4241.28,
            "win_rate": 59.33,
            "trades": 927,
            "max_drawdown_pct": 7.65,
            "longest_consecutive_losses": 6,
        },
    },
    "ADAUSDT": {
        "strategy_name": "frama_cross",
        "take_profit_pct": 9.0,
        "stop_loss_pct": 5.0,
        "trailing_activation_pct": 4.0,
        "trailing_distance_pct": 0.15,
        "default_leverage": 20,
        "strategy_params": {"frama_fast_period": 12.0, "frama_slow_period": 34.0},
        "audit_meta": {
            "profit_factor": 1.48,
            "pnl": 2822.59,
            "win_rate": 60.49,
            "trades": 577,
            "max_drawdown_pct": 15.1,
            "longest_consecutive_losses": 7,
        },
    },
    "DOGEUSDT": {
        "strategy_name": "frama_cross",
        "take_profit_pct": 12.0,
        "stop_loss_pct": 5.0,
        "trailing_activation_pct": 5.0,
        "trailing_distance_pct": 0.15,
        "default_leverage": 20,
        "strategy_params": {"frama_fast_period": 10.0, "frama_slow_period": 21.0},
        "audit_meta": {
            "profit_factor": 1.63,
            "pnl": 5047.03,
            "win_rate": 62.04,
            "trades": 598,
            "max_drawdown_pct": 8.33,
            "longest_consecutive_losses": 7,
        },
    },
    "BNBUSDT": {
        "strategy_name": "ema_cross_volume",
        "take_profit_pct": 8.0,
        "stop_loss_pct": 4.5,
        "trailing_activation_pct": 4.0,
        "trailing_distance_pct": 0.2,
        "default_leverage": 20,
        "strategy_params": {"ema_fast_period": 13.0, "ema_slow_period": 34.0},
        "audit_meta": {
            "profit_factor": 1.26,
            "pnl": 1552.15,
            "win_rate": 21.37,
            "trades": 655,
            "max_drawdown_pct": 11.86,
            "longest_consecutive_losses": 14,
        },
    },
    "AVAXUSDT": {
        "strategy_name": "frama_cross",
        "take_profit_pct": 9.0,
        "stop_loss_pct": 5.5,
        "trailing_activation_pct": 4.0,
        "trailing_distance_pct": 0.15,
        "default_leverage": 20,
        "strategy_params": {"frama_fast_period": 8.0, "frama_slow_period": 21.0},
        "audit_meta": {
            "profit_factor": 1.42,
            "pnl": 3470.82,
            "win_rate": 63.61,
            "trades": 709,
            "max_drawdown_pct": 13.19,
            "longest_consecutive_losses": 6,
        },
    },
    "NEARUSDT": {
        "strategy_name": "dual_thrust",
        "take_profit_pct": 6.0,
        "stop_loss_pct": 5.0,
        "trailing_activation_pct": 5.0,
        "trailing_distance_pct": 0.15,
        "default_leverage": 25,
        "strategy_params": {"dual_thrust_k1": 0.6, "dual_thrust_k2": 0.6, "dual_thrust_period": 34.0},
        "audit_meta": {
            "profit_factor": 0.0,
            "pnl": 0.0,
            "win_rate": 0.0,
            "trades": 0,
            "max_drawdown_pct": 0.0,
            "longest_consecutive_losses": 0,
        },
    },
    "DOTUSDT": {
        "strategy_name": "frama_cross",
        "take_profit_pct": 9.0,
        "stop_loss_pct": 5.0,
        "trailing_activation_pct": 4.0,
        "trailing_distance_pct": 0.15,
        "default_leverage": 20,
        "strategy_params": {"frama_fast_period": 8.0, "frama_slow_period": 34.0},
        "audit_meta": {
            "profit_factor": 1.44,
            "pnl": 3697.45,
            "win_rate": 65.08,
            "trades": 653,
            "max_drawdown_pct": 7.94,
            "longest_consecutive_losses": 6,
        },
    },
}
